# Generated by Django 2.0.2 on 2018-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='codigo_postal_text',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='localidade_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='morada_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assistencia',
            name='descricao_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assistencia',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email_text',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone_text',
            field=models.IntegerField(blank=True),
        ),
    ]
