# Generated by Django 2.0.2 on 2018-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0002_auto_20180220_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='numserie_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
