# Generated by Django 2.0.2 on 2018-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0003_auto_20180220_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
