# Generated by Django 2.0.2 on 2018-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0004_auto_20180221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='assistencias',
            field=models.ManyToManyField(blank=True, null=True, to='assistencias.Assistencia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='codigo_postal_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email_text',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='localidade_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='morada_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone_text',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
